ersion: 1.0.{build}
build_script:
- cmd: >-
    cd FintFellesModel

    dotnet restore

    dotnet build
    
before_deploy:
- cmd: nuget pack FintFellesModel.nuspec

deploy:
- provider: BinTray
  username: eidjord
  api_key:
    secure: kAQ1TMYLfOwSpyCyaYGs7jBG/7+c+YVOHbqFGuN0Bpg6tOKaq7g2bCIgjia/84gB
  subject: fint
  repo: nuget
  package: fint-model-arbeidstaker-csharp
  artifact: /.*\.nupkg/
  publish: true
  override: true